param(
    [switch]$UseLocalEnv  # Use local .env file instead of embedded token (development)
)
# ================================
# Snipe-IT Auto-Registration
# - Single-file deployment: API token is AES-256 encrypted and embedded below
# - Requires passphrase at runtime (no static secrets on disk)
# - Use -UseLocalEnv switch for development with local .env file
# - No automatic checkout: asset is created/updated and left unassigned
# - Robust status-label handling (find, update, fallback create)
# - Category: Notebook / Desktop (auto-detected)
# - Manufacturer via WMI (find-or-create)
# - Custom fields: only sent if present in the model's fieldset
# ================================

# ==== CONFIG ====
$SnipeUrl = "https://snipe-it.cci.drexel.edu"

# ==== ENCRYPTED API TOKEN ====
# Generated by Encrypt-Token.ps1 - requires passphrase to decrypt
# To update: run Encrypt-Token.ps1 and replace this value

# If Snipe-IT API key is ever changed, run Encrypt-Token.ps1 to generate a new encrypted token.
# Then, replace this value with the new encrypted token BASE64 string.
$EncryptedTokenBase64 = "AAAAAAAAAAAAAAAAAAAAABkt5Xo13HBamrsq6l3j5I9mLxn3uUeHAHghwJ9LPY8BifDrZeUOllbeQpb7YdzBtxHuLuitj6lAVvQg9h4PqZjpjbumaOSJzp6SwbVU0AzHQ1dgEN5sw3mMpvOG5omnjZvurP1Lyv90eiHyu94GgyRCCAutEw080AktvhX/ueIMLNw62SPeGYjg4X98/R8yW4TJpM5hH4dNGYlGsEiZ2u+2bY8VEEeyEEbxiXZ2wYiBgdJKXWDy3hiApTQkfjBoYf5E3TRJca2KWU1GLtgCYNiv8qPp7i8wcTEOdCwHAzIKByHPVQcN3zjv8iTdjRk7hmBfYVX5Pq9aSjx+fKg8jazjYYxhL6XrndRqYlcJxpTmedEs/D9lignaA0uZ68cRTq2NwFwfbTkY8+5lZr3MAs6A4QNBJos2sKbjaLFG5AJW0XbGwdhclh3zsmQKfwvbCyi5+L6FZodN+UBODBao23a9RIYUT5oUY0DKDKhDKVQ7JXia0CO33fcyslae4lsnR92NqE2B6HH5uMV7qynz96mOVbzBooZcQszeMKC6obZavaXxkK8k10Cn2LnY37Koja+HNzCGRJmLcOjPs5UAC6w9SN1E8kEd+0GOdBFmo5Nbvo4IyrZI+tGfK/fb/Ar8JSs3zc32CM9FXg31wUlRMG85DWdWFY12owT4YP1v/6X2HhCr+JCUwzQvp/yrsq1J+2xdMXNwJens+M6NnPqQq4MxcHGqkiDM7RvpdusDH3lZFGnzQeSX9/R1d3506KNcATHf/gjSNdS8WWxUrDfJNuQ0xhURpF+VR80pyJPB/ORWLgSwCUenq+A0pfUerHZi9ZyBpG/+9U3lnugsWpyPioqoKLrbz7wpsYAky59gM8wbnrkLQe8eu2ei7C0trDi40olCFhVWKBcNvZHQIvyZ+23Zd4csVVzrf5BtJGraUrfEEzXxek9acM/8QsVf+r7hJIIJtgItVXmzsieNIZ3u2NL2UhSqU2/ggkwztrjiFAMkQmmOfNkubralVL/sSlQNcSaLdJf3iw5h+ZzSjZsvSLVOxNETuLNCCd7xKEXywo0lWvaMy+Sdf6NAp/iVzdGstrCpwQYFK7CDzx7zn5FTJXzfSV7tiCS/LdiThKDe5QoqhR6jtGaNSo02ZVEHSh7oUsXKPC9lYD2M9OD+5GtrGEFuYv0i/+PhUACJVuUj5jxv8VrVbzLVuyJIki17j/7XctLCowNZnpxpSJiPK3OOr5oR4kLews85HO3BKLkgFCj+JN6v+jz/MxHxxUfHIRvO1yhA8bfxgWstM2GLzGeIB9tdXY1Hufvc2QydVK057VKz"

function Get-EnvValue {
    # Reads a single KEY=value line out of a local .env file.
    # Testing convenience only. NOT part of public design.
    param(
        [Parameter(Mandatory)][string] $Key,
        [string] $EnvPath = ".\.env"
    )
    if (-not (Test-Path $EnvPath)) {
        throw "Could not find .env file at '$EnvPath'."
    }
    $line = (Select-String -Path $EnvPath -Pattern "^$Key\s*=").Line
    if (-not $line) {
        throw "Key '$Key' not found in '$EnvPath'."
    }
    $value = ($line -split '=', 2 | Select-Object -Last 1)
    return $value.Trim().Trim('"').Trim("'")
}

function Get-ApiTokenFromEmbedded {
    param(
        [Parameter(Mandatory)][string]$EncryptedBase64
    )
    
    # Validate Base64 string is not empty.
    if ($EncryptedBase64 -eq "PASTE_BASE64_STRING_HERE" -or [string]::IsNullOrWhiteSpace($EncryptedBase64)) {
        throw "Encrypted token not configured. Run Encrypt-Token.ps1 and paste the output into `$EncryptedTokenBase64."
    }
    
    # Prompt for passphrase
    $Passphrase = Read-Host -Prompt "Enter passphrase to decrypt API token" -AsSecureString # Returns SecureString object
    $BSTR = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($Passphrase) # Converts SecureString object to a BSTR (Binary String Representation)
    $PassphraseText = [Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR) # Converts BSTR to a string
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($BSTR) # Clears the BSTR from memory
    
    # Decode Base64 to bytes (salt + ciphertext)
    $EncryptedData = [Convert]::FromBase64String($EncryptedBase64)
    $Salt = $EncryptedData[0..15]
    $Ciphertext = $EncryptedData[16..($EncryptedData.Length - 1)]
    
    # Derive key using same PBKDF2 parameters
    $KeyDerivation = New-Object Security.Cryptography.Rfc2898DeriveBytes(
        $PassphraseText, $Salt, 100000, [Security.Cryptography.HashAlgorithmName]::SHA256)
    $Key = $KeyDerivation.GetBytes(32)
    $IV = $KeyDerivation.GetBytes(16)
    
    # Clear passphrase
    $PassphraseText = $null
    [GC]::Collect()
    
    # Decrypt
    try {
        $Aes = [Security.Cryptography.Aes]::Create()
        $Aes.Key = $Key
        $Aes.IV = $IV
        $Aes.Mode = [Security.Cryptography.CipherMode]::CBC
        $Aes.Padding = [Security.Cryptography.PaddingMode]::PKCS7
        
        $Decryptor = $Aes.CreateDecryptor()
        $DecryptedBytes = $Decryptor.TransformFinalBlock($Ciphertext, 0, $Ciphertext.Length)
        $Aes.Dispose()
        
        $Token = [Text.Encoding]::UTF8.GetString($DecryptedBytes).Trim()
        if ([string]::IsNullOrWhiteSpace($Token)) {
            throw "Decrypted token is empty."
        }
        return $Token
    } catch {
        throw "Decryption failed - wrong passphrase or corrupted data."
    }
}

if ($UseLocalEnv) {
    $ApiToken = Get-EnvValue -Key "snipe-it_api_key"
    Write-Host "Using local .env file for API token (development mode)" -ForegroundColor Yellow
} else {
    try {
        $ApiToken = Get-ApiTokenFromEmbedded -EncryptedBase64 $EncryptedTokenBase64
        Write-Host "API token decrypted successfully." -ForegroundColor Green
    } catch {
        Write-Error "Failed to decrypt API token: $($_.Exception.Message)"
        Write-Host "Hint: Run with -UseLocalEnv to use a local .env file for development." -ForegroundColor Yellow
        exit 1
    }
}

$CategoryNameNotebook = "Laptop"
$CategoryNameDesktop  = "Desktop/Stationary/AIO"
# $CategoryNameServer   = "Server"
$DesiredDeployLabelName = "Loaner Equipment"              # preferred name (will try to use)
$FallbackNewLabelName   = "Loaner Equipment" # created if nothing suitable exists

$CompanyId  = $null
$LocationId = $null
$UseManufacturerFromWmi = $true

# Known custom fields (only sent if present in the model's fieldset)
# Hardware spec custom fields
$CF_RAM         = "_snipeit_ram_4"           
$CF_CPU         = "_snipeit_cpu_5"           
$CF_MEMORY_SSD  = "_snipeit_memory_ssd_6"    
$CF_MEMORY_HDD  = "_snipeit_memory_hdd_7"   
$CF_GPU         = "_snipeit_gpu_8"           
$CF_UUID        = "_snipeit_uuid_9"          

# ==== HTTP ====
$Headers = @{
  "Authorization" = "Bearer $ApiToken"
  "Accept"        = "application/json"
  "Content-Type"  = "application/json"
}

function Invoke-SnipeApi {
  param(
    [Parameter(Mandatory)][ValidateSet("GET","POST","PATCH","PUT","DELETE")] [string] $Method,
    [Parameter(Mandatory)] [string] $Endpoint,
    [hashtable] $Body = $null
  )
  $uri = "$SnipeUrl/api/v1/$Endpoint"
  Write-Host "API $Method $Endpoint" -ForegroundColor Cyan
  try {
    if ($Body) {
      $json = ($Body | ConvertTo-Json -Depth 7)
      Write-Host "Body: $json" -ForegroundColor DarkGray
      $resp = Invoke-RestMethod -Method $Method -Uri $uri -Headers $Headers -Body $json -ErrorAction Stop
    } else {
      $resp = Invoke-RestMethod -Method $Method -Uri $uri -Headers $Headers -ErrorAction Stop
    }
    if ($resp.status -or $resp.messages) {
      Write-Host ("Result: status={0} messages={1}" -f $resp.status, (($resp.messages -join " | "))) -ForegroundColor Yellow
    }
    return $resp
  } catch {
    Write-Warning "API error $Method $Endpoint : $($_.Exception.Message)"
    if ($_.Exception.Response -and $_.Exception.Response.GetResponseStream()) {
      $sr = New-Object System.IO.StreamReader($_.Exception.Response.GetResponseStream())
      $respText = $sr.ReadToEnd()
      Write-Warning "Response body: $respText"
    }
    throw
  }
}

# ==== Utils ====
function Get-EntityIdFromResponse {
  param([Parameter(Mandatory)] $Response)
  if ($Response.id) { return [int]$Response.id }
  if ($Response.payload -and $Response.payload.id) { return [int]$Response.payload.id }
  return $null
}

# ==== System info ====
$Hostname = $env:COMPUTERNAME
$Username = $env:USERNAME  # kept for logging only -- no longer used for checkout

$Bios   = Get-CimInstance -Class Win32_BIOS -ErrorAction SilentlyContinue
$Serial = ($Bios.SerialNumber | ForEach-Object { $_.Trim() }) -join ""
if (-not $Serial) { throw "Could not determine serial number." }

$CS          = Get-CimInstance -Class Win32_ComputerSystem -ErrorAction SilentlyContinue
$ModelNumber = ($CS.Model | ForEach-Object { $_.Trim() }) -join ""
if (-not $ModelNumber) { $ModelNumber = "Unknown model" }

$WmiManufacturer = ($CS.Manufacturer | ForEach-Object { $_.Trim() }) -join ""
if (-not $WmiManufacturer) { $WmiManufacturer = "Unknown" }
switch -Regex ($WmiManufacturer) {
  "^(Hewlett Packard Enterprise|HPE)$"  { $WmiManufacturer = "HPE"; break }
  "^(Hewlett-Packard|Hewlett Packard)$" { $WmiManufacturer = "HP"; break }
  "^(Dell).*"     { $WmiManufacturer = "Dell"; break }
  "^(Lenovo).*"   { $WmiManufacturer = "Lenovo"; break }
  default { }
}

$Enclosure    = Get-CimInstance -Class Win32_SystemEnclosure -ErrorAction SilentlyContinue
$ChassisTypes = if ($Enclosure.ChassisTypes) { $Enclosure.ChassisTypes } else { @() }
$IsNotebook   = $false
if ($ChassisTypes) { $IsNotebook = $ChassisTypes | Where-Object { $_ -in 8,9,10,14 } | ForEach-Object { $true } | Select-Object -First 1 }
if (-not $ChassisTypes) { if (Get-CimInstance -Class Win32_Battery -ErrorAction SilentlyContinue) { $IsNotebook = $true } }
# $IsServerModel = $false
# if ($ModelNumber -match '(ProLiant|PowerEdge|ThinkSystem|PRIMERGY|ThinkServer)') { $IsServerModel = $true }

# Get RAM capacity and speed
$RamModules = Get-CimInstance -Class Win32_PhysicalMemory -ErrorAction SilentlyContinue
$RamCapacityGB = if ($RamModules) { [math]::Round(($RamModules | Measure-Object -Property Capacity -Sum).Sum / 1GB, 1) } else { $null }
$RamSpeedMHz = if ($RamModules) { ($RamModules | Select-Object -First 1).Speed } else { $null }
$Ram = if ($RamCapacityGB -and $RamSpeedMHz) { [string]"$RamCapacityGB GB $RamSpeedMHz MHz" } elseif ($RamCapacityGB) { [string]"$RamCapacityGB GB" } else { $null }
$Cpu = (Get-CimInstance -Class Win32_Processor -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty Name)
$MemorySsd = Get-PhysicalDisk | Select-Object FriendlyName, MediaType, @{Name="Size(GB)";Expression={[math]::Round($_.Size/1GB,2)}}
$MemorySsd = $MemorySsd | Where-Object { $_.MediaType -eq "SSD" } | Measure-Object -Property "Size(GB)" -Sum | ForEach-Object { [math]::Round($_.Sum, 2) }
$MemoryHdd = Get-PhysicalDisk | Select-Object FriendlyName, MediaType, @{Name="Size(GB)";Expression={[math]::Round($_.Size/1GB,2)}}
$MemoryHdd = $MemoryHdd | Where-Object { $_.MediaType -eq "HDD" } | Measure-Object -Property "Size(GB)" -Sum | ForEach-Object { [math]::Round($_.Sum, 2) }
$Gpu = (Get-CimInstance -Class Win32_VideoController -ErrorAction SilentlyContinue).VideoProcessor | Where-Object { $_ -and $_.Trim() -ne "" }
$Gpu = if ($Gpu) { ($Gpu -join ", ") } else { $null }
$Uuid = (Get-CimInstance -Class Win32_ComputerSystemProduct -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty UUID)

# Model name is the actual WMI model string (e.g. "Latitude 3400", "OptiPlex 7000 Micro"),
$ModelName = $ModelNumber

# Format hardware specs for display
$RamDisplay = if ($Ram) { $Ram } else { "N/A" }
$CpuDisplay = if ($Cpu) { $Cpu } else { "N/A" }
$SsdDisplay = if ($MemorySsd) { "$MemorySsd GB" } else { "N/A" }
$HddDisplay = if ($MemoryHdd) { "$MemoryHdd GB" } else { "N/A" }
$GpuDisplay = if ($Gpu) { $Gpu } else { "N/A" }
$UuidDisplay = if ($Uuid) { $Uuid } else { "N/A" }

Write-Host "========== DETECTED SYSTEM INFO ==========" -ForegroundColor Cyan
Write-Host "  Hostname:     $Hostname" -ForegroundColor Green
Write-Host "  Serial:       $Serial" -ForegroundColor Green
Write-Host "  Model:        $ModelNumber" -ForegroundColor Green
Write-Host "  Manufacturer: $WmiManufacturer" -ForegroundColor Green
Write-Host "  Type:         $(if ($IsNotebook) { 'Laptop' } else { 'Desktop' })" -ForegroundColor Green
Write-Host "========== HARDWARE SPECS ==========" -ForegroundColor Cyan
Write-Host "  RAM:          $RamDisplay" -ForegroundColor Green
Write-Host "  CPU:          $CpuDisplay" -ForegroundColor Green
Write-Host "  SSD:          $SsdDisplay" -ForegroundColor Green
Write-Host "  HDD:          $HddDisplay" -ForegroundColor Green
Write-Host "  GPU:          $GpuDisplay" -ForegroundColor Green
Write-Host "  UUID:         $UuidDisplay" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Cyan

# ==== API helpers ====
function FindOrCreateCategory {
  param([string] $Name)
  $res = Invoke-SnipeApi -Method GET -Endpoint ("categories?search={0}&limit=100" -f [uri]::EscapeDataString($Name))
  $cat = $null
  if ($res.total -gt 0) { $cat = $res.rows | Where-Object { $_.name -eq $Name } | Select-Object -First 1 }
  if ($cat) { return $cat }
  return Invoke-SnipeApi -Method POST -Endpoint "categories" -Body @{ name = $Name; category_type = "asset" }
}

function FindOrCreateManufacturer {
  param([string] $Name)
  if ([string]::IsNullOrWhiteSpace($Name) -or $Name -eq "Unknown") { return $null }
  $res = Invoke-SnipeApi -Method GET -Endpoint ("manufacturers?search={0}&limit=100" -f [uri]::EscapeDataString($Name))
  $m = $null
  if ($res.total -gt 0) {
    $m = $res.rows | Where-Object { $_.name -eq $Name } | Select-Object -First 1
    if (-not $m) { $m = $res.rows | Select-Object -First 1 }
  }
  if ($m) { return $m }
  return Invoke-SnipeApi -Method POST -Endpoint "manufacturers" -Body @{ name = $Name }
}

# Finds a deployable status label; repairs/creates one if needed
function FindOrCreateDeployableStatusLabel {
  param([string] $PreferredName, [string] $NewNameIfNeeded)

  function Test-IsDeployable($lbl) {
    if ($null -eq $lbl) { return $false }
    if ($lbl.PSObject.Properties.Name -contains 'status_type' -and $lbl.status_type -eq 'deployable') { return $true }
    if ($lbl.PSObject.Properties.Name -contains 'type'        -and $lbl.type        -eq 'deployable') { return $true }
    if ($lbl.PSObject.Properties.Name -contains 'deployable'  -and $lbl.deployable  -eq $true)        { return $true }
    return $false
  }

  function Try-UpdateToDeployable($id, $name) {
    try {
      $null = Invoke-SnipeApi -Method PUT -Endpoint ("statuslabels/{0}" -f $id) -Body @{ name = $name; status_type = "deployable" }
      return $true
    } catch { Write-Warning "PUT status_type failed: $($_.Exception.Message)" }

    try {
      $null = Invoke-SnipeApi -Method PUT -Endpoint ("statuslabels/{0}" -f $id) -Body @{ name = $name; type = "deployable" }
      return $true
    } catch { Write-Warning "PUT type=deployable failed: $($_.Exception.Message)" }

    try {
      $null = Invoke-SnipeApi -Method PATCH -Endpoint ("statuslabels/{0}" -f $id) -Body @{ deployable = $true; pending = $false; archived = $false }
      return $true
    } catch { Write-Warning "PATCH deployable/pending/archived failed: $($_.Exception.Message)" }

    return $false
  }

  function Try-CreateDeployable {
    param([string] $name)
    try {
      return Invoke-SnipeApi -Method POST -Endpoint "statuslabels" -Body @{ name = $name; status_type = "deployable" }
    } catch { Write-Warning "POST status_type=deployable failed: $($_.Exception.Message)" }
    try {
      return Invoke-SnipeApi -Method POST -Endpoint "statuslabels" -Body @{ name = $name; type = "deployable" }
    } catch { Write-Warning "POST type=deployable failed: $($_.Exception.Message)" }
    try {
      return Invoke-SnipeApi -Method POST -Endpoint "statuslabels" -Body @{ name = $name; deployable = $true; pending = $false; archived = $false }
    } catch { Write-Warning "POST legacy flags failed: $($_.Exception.Message)" }
    return $null
  }

  # 1) Try the preferred name first
  $res = Invoke-SnipeApi -Method GET -Endpoint ("statuslabels?search={0}&limit=100" -f [uri]::EscapeDataString($PreferredName))
  if ($res.total -gt 0) {
    $label = $res.rows | Where-Object { $_.name -eq $PreferredName } | Select-Object -First 1
    if ($label -and (Test-IsDeployable $label)) { return $label }
    if ($label -and -not (Test-IsDeployable $label)) {
      if (Try-UpdateToDeployable -id $label.id -name $label.name) {
        $refreshed = Invoke-SnipeApi -Method GET -Endpoint ("statuslabels/{0}" -f $label.id)
        if (Test-IsDeployable $refreshed) { return $refreshed }
      }
      return $label
    }
  }

  # 2) Find any existing deployable label
  $all = Invoke-SnipeApi -Method GET -Endpoint "statuslabels?limit=100"
  if ($all.total -gt 0) {
    $deploy = $all.rows | Where-Object { Test-IsDeployable $_ } | Select-Object -First 1
    if ($deploy) { return $deploy }
  }

  # 3) Nothing found -> create one (tries all variants)
  Write-Host "No deployable status label found -> creating '$NewNameIfNeeded'..." -ForegroundColor Magenta
  $created = Try-CreateDeployable -name $NewNameIfNeeded
  if ($created -and (Test-IsDeployable $created)) { return $created }

  throw "Could not determine or create a deployable status label."
}

function FindOrCreateModel {
  param(
    [string] $Name, [string] $ModelNumber, [int] $CategoryId, [int] $ManufacturerId = $null
  )

  # Try to search by model name first
  $resName = Invoke-SnipeApi -Method GET -Endpoint ("models?limit=100&search={0}" -f [uri]::EscapeDataString($Name))
  if ($resName.total -gt 0) {
    $hit = $resName.rows | Where-Object { $_.name -eq $Name } | Select-Object -First 1
    if ($hit) {
      Write-Host "Found existing model by name: $($hit.name) (ID $($hit.id))" -ForegroundColor Green
      return $hit
    }
  }

  # If no model is found by name, prompt user before creating
  Write-Host "========== MODEL NOT FOUND ==========" -ForegroundColor Yellow
  Write-Host "No existing model found with name: $Name" -ForegroundColor Yellow
  Write-Host "A new model will be created with:" -ForegroundColor Yellow
  Write-Host "  Name:         $Name" -ForegroundColor Yellow
  Write-Host "  Model Number: $ModelNumber" -ForegroundColor Yellow
  Write-Host "  Category ID:  $CategoryId" -ForegroundColor Yellow
  if ($ManufacturerId) { Write-Host "  Manufacturer ID: $ManufacturerId" -ForegroundColor Yellow }
  Write-Host "=====================================" -ForegroundColor Yellow
  
  $modelResponse = Read-Host -Prompt "Create this new model? (y/n)"
  if ($modelResponse -ne "y") {
    Write-Host "Model creation aborted by user." -ForegroundColor Red
    throw "Model creation cancelled. Cannot proceed without a valid model."
  }

  Write-Host "Creating new model..." -ForegroundColor Magenta
  $body = @{ name=$Name; model_number=$ModelNumber; category_id=$CategoryId }
  if ($ManufacturerId) { $body.manufacturer_id = [int]$ManufacturerId }
  $created = $null
  try {
    $created = Invoke-SnipeApi -Method POST -Endpoint "models" -Body $body
  } catch {
    Write-Warning "Model creation failed. Verifying via lookup..."
  }
  if ($created) {
    $newId = Get-EntityIdFromResponse -Response $created
    if ($newId) {
      $full = Invoke-SnipeApi -Method GET -Endpoint ("models/{0}" -f $newId)
      if ($full -and $full.id) { return $full }
    }
  }
  $res2 = Invoke-SnipeApi -Method GET -Endpoint ("models?limit=100&search={0}" -f [uri]::EscapeDataString($ModelNumber))
  if ($res2.total -gt 0) {
    $mdl = $res2.rows | Where-Object { $_.model_number -eq $ModelNumber } | Select-Object -First 1
    if ($mdl) { return $mdl }
  }
  # broader search fallback
  $res3 = Invoke-SnipeApi -Method GET -Endpoint ("models?limit=100&search={0}" -f [uri]::EscapeDataString(($ModelNumber -split '\s+')[0]))
  if ($res3.total -gt 0) {
    $mdl = $res3.rows | Where-Object { $_.model_number -eq $ModelNumber } | Select-Object -First 1
    if ($mdl) { return $mdl }
  }
  throw "Could not find/create a matching model (Name='$Name' ModelNumber='$ModelNumber')."
}

function GetModelFieldsetColumns {
  param([int] $ModelId)
  $full = Invoke-SnipeApi -Method GET -Endpoint ("models/{0}" -f $ModelId)

  # Some Snipe-IT versions embed the fields directly on the model's fieldset object;
  # most don't -- the model response usually only carries the fieldset's id/name.
  if ($full -and $full.fieldset -and $full.fieldset.fields -and $full.fieldset.fields.rows) {
    $cols = $full.fieldset.fields.rows | ForEach-Object { $_.db_column_name } | Where-Object { $_ }
    if ($cols) {
      Write-Host "Fieldset columns (embedded): $($cols -join ', ')" -ForegroundColor DarkGray
      return $cols
    }
  }

  # Fallback: resolve the fieldset id and fetch it directly, where the field list actually lives.
  $fieldsetId = $null
  if ($full -and $full.fieldset -and $full.fieldset.id) { $fieldsetId = [int]$full.fieldset.id }
  elseif ($full -and $full.fieldset_id) { $fieldsetId = [int]$full.fieldset_id }

  if (-not $fieldsetId) {
    Write-Host "Model $ModelId has no fieldset assigned -- no custom fields will be sent." -ForegroundColor DarkGray
    return @()
  }

  $fs = Invoke-SnipeApi -Method GET -Endpoint ("fieldsets/{0}" -f $fieldsetId)
  $cols = @()
  if ($fs -and $fs.fields -and $fs.fields.rows) {
    $cols = $fs.fields.rows | ForEach-Object { $_.db_column_name } | Where-Object { $_ }
  }
  Write-Host "Fieldset columns (via fieldsets/$fieldsetId): $($cols -join ', ')" -ForegroundColor DarkGray
  return $cols
}

function GetAssetBySerial {
  param([string] $Serial)
  try {
    $res = Invoke-SnipeApi -Method GET -Endpoint ("hardware/byserial/{0}" -f [uri]::EscapeDataString($Serial))
    if ($res -and $res.id) { return $res }
  } catch { }
  $res2 = Invoke-SnipeApi -Method GET -Endpoint ("hardware?search={0}&limit=50" -f [uri]::EscapeDataString($Serial))
  if ($res2.total -gt 0) { return $res2.rows | Where-Object { $_.serial -eq $Serial } | Select-Object -First 1 }
  return $null
}

function CreateOrUpdateAsset {
  # No checkout: asset is created/updated and left unassigned.
  param([string] $Name, [string] $Serial, [int] $ModelId, [int] $StatusId)

  # Only send custom fields that this model's fieldset actually has --
  # AND only when we actually detected a value. Sending a null for a
  # required field fails the same way as not sending it, just less
  # predictably, so skip it and warn instead.
  $allowedCF = @(GetModelFieldsetColumns -ModelId $ModelId)
  $custom = @{}
  if ($allowedCF -contains $CF_RAM -and $Ram)               { $custom[$CF_RAM]        = [string]$Ram }
  if ($allowedCF -contains $CF_CPU -and $Cpu)               { $custom[$CF_CPU]        = [string]$Cpu }
  if ($allowedCF -contains $CF_MEMORY_SSD -and $MemorySsd)  { $custom[$CF_MEMORY_SSD] = [string]$MemorySsd }
  if ($allowedCF -contains $CF_MEMORY_HDD -and $MemoryHdd)  { $custom[$CF_MEMORY_HDD] = [string]$MemoryHdd }
  if ($allowedCF -contains $CF_GPU -and $Gpu)               { $custom[$CF_GPU]        = [string]$Gpu }
  if ($allowedCF -contains $CF_UUID -and $Uuid)             { $custom[$CF_UUID]       = [string]$Uuid }

  $skipped = $allowedCF | Where-Object { $_ -notin $custom.Keys }
  if ($skipped) {
    Write-Warning "Fieldset has these columns but no value was detected for them (not sent -- may fail if marked Required): $($skipped -join ', ')"
  }

  $existing = GetAssetBySerial -Serial $Serial
  if ($existing) {
    Write-Host "Asset with SN '$Serial' already exists (ID $($existing.id)) -- updating..." -ForegroundColor Green
    $updBody = @{ model_id=[int]$ModelId; status_id=[int]$StatusId } + $custom
    if ($CompanyId)  { $updBody.company_id  = [int]$CompanyId }
    if ($LocationId) { $updBody.location_id = [int]$LocationId }
    $ru = Invoke-SnipeApi -Method PATCH -Endpoint ("hardware/{0}" -f $existing.id) -Body $updBody
    if ($ru.status -and $ru.status -ne "success") { throw "Update failed: $($ru | ConvertTo-Json -Depth 7)" }
    return GetAssetBySerial -Serial $Serial
  } else {
    Write-Host "Creating new asset..." -ForegroundColor Green
    $body = @{ name=$Name; serial=$Serial; model_id=[int]$ModelId; status_id=[int]$StatusId } + $custom
    if ($CompanyId)  { $body.company_id  = [int]$CompanyId }
    if ($LocationId) { $body.location_id = [int]$LocationId }

    $created = Invoke-SnipeApi -Method POST -Endpoint "hardware" -Body $body
    if ($created.status -and $created.status -ne "success") { throw "Creation failed: $($created | ConvertTo-Json -Depth 7)" }
    $assetId = Get-EntityIdFromResponse -Response $created
    if (-not $assetId) {
      # Fallback: look it up by serial
      $ref = GetAssetBySerial -Serial $Serial
      if ($ref -and $ref.id) { $assetId = [int]$ref.id }
    }
    if (-not $assetId) { throw "Creation returned no asset ID and lookup failed: $($created | ConvertTo-Json -Depth 7)" }

    return GetAssetBySerial -Serial $Serial
  }
}

# ==== Main flow ====
$status = FindOrCreateDeployableStatusLabel -PreferredName $DesiredDeployLabelName -NewNameIfNeeded $FallbackNewLabelName

$statusInfo = ""
if ($null -ne $status.status_type -and $status.status_type -ne "") {
    $statusInfo = "type=$($status.status_type)"
} elseif ($status.PSObject.Properties.Name -contains 'deployable') {
    $statusInfo = "deployable=$($status.deployable)"
}
Write-Host "Deployable status label: $($status.name) (ID $($status.id)) $statusInfo" -ForegroundColor Green

$catName = if ($IsNotebook) { $CategoryNameNotebook } else { $CategoryNameDesktop }
$cat = FindOrCreateCategory -Name $catName
Write-Host "Category: $($cat.name) (ID $($cat.id))" -ForegroundColor Green

$manuId = $null
if ($UseManufacturerFromWmi -and $WmiManufacturer -and $WmiManufacturer -ne "Unknown") {
  $manu = FindOrCreateManufacturer -Name $WmiManufacturer
  if ($manu -and $manu.id) {
    $manuId = [int]$manu.id
    Write-Host "Manufacturer: $($manu.name) (ID $($manu.id))" -ForegroundColor Green
  }
}

# Model name follows the format: "Manufacturer Model Number." Example: "Latitude 3400"
$model = FindOrCreateModel -Name $ModelName -ModelNumber $ModelNumber -CategoryId ([int]$cat.id) -ManufacturerId $manuId
Write-Host "Model: $($model.name) ($($model.model_number)) (ID $($model.id))" -ForegroundColor Green

Write-Host "The following asset will be created/updated: $Hostname | $Serial | $ModelName | $ModelNumber | $WmiManufacturer" -ForegroundColor Yellow
$response = Read-Host -Prompt "Continue? (y/n) ENSURE THE CORRECT MODEL IS SELECTED BEFORE CONTINUING!"
if ($response -ne "y") {
  Write-Host "Aborted." -ForegroundColor Red
  exit 1
}
$asset = CreateOrUpdateAsset -Name $Hostname -Serial $Serial -ModelId ([int]$model.id) -StatusId ([int]$status.id)

Write-Host "Done. Asset ID: $($asset.id) | Name: $($asset.name) | Left unassigned (no auto-checkout)." -ForegroundColor Green
Write-Host "Direct link: $SnipeUrl/hardware/$($asset.id)"